### ISSUE TITLE
Contrast error 508 testing

### ISSUE THREAD

**Issue by rohith33reddy** [GSA/sam-styles#583]
I was using WAVE tool to do 508 testing and saw this contrast error for Select a Role drop down field. 
![image](https://user-images.githubusercontent.com/117935058/201192980-65dd0571-24e5-43e7-a9bb-90cabbad89f2.png)

**Comment by davereed** [comment]
Hi @rohith33reddy, please elaborate on what you would like done for this. The screenshot shows that the label is totally hidden, not that there is a contrast problem. If you are hiding the label on purpose we need to know how this is configured and whether the issue has been debugged to know if the problem is at the common component level or within your implementation.
